# Generated by Django 4.0.6 on 2024-02-10 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('Done', 'done'), ('Postponed', 'postponed'), ('In progess', 'progess'), ('Canceled', 'canceled')], max_length=15, verbose_name='Status'),
        ),
    ]
